wget -P /root/Bucore/.minecraft/libraries/com/mojang/patchy/1.1/ https://libraries.minecraft.net/com/mojang/patchy/1.1/patchy-1.1.jar
wget -P /root/Bucore/.minecraft/libraries/oshi-project/oshi-core/1.1/ https://libraries.minecraft.net/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
wget -P /root/Bucore/.minecraft/libraries/net/java/dev/jna/jna/4.4.0/ https://libraries.minecraft.net/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
wget -P /root/Bucore/.minecraft/libraries/net/java/dev/jna/platform/3.4.0/ https://libraries.minecraft.net/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
wget -P /root/Bucore/.minecraft/libraries/com/ibm/icu/icu4j-core-mojang/51.2/ https://libraries.minecraft.net/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
wget -P /root/Bucore/.minecraft/libraries/com/mojang/javabridge/1.0.22/ https://libraries.minecraft.net/com/mojang/javabridge/1.0.22/javabridge-1.0.22.jar
wget -P /root/Bucore/.minecraft/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/ https://libraries.minecraft.net/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
wget -P /root/Bucore/.minecraft/libraries/io/netty/netty-all/4.1.25.Final/ https://libraries.minecraft.net/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar
wget -P /root/Bucore/.minecraft/libraries/com/google/guava/guava/21.0/ https://libraries.minecraft.net/com/google/guava/guava/21.0/guava-21.0.jar
wget -P /root/Bucore/.minecraft/libraries/org/apache/commons/commons-lang3/3.5/ https://libraries.minecraft.net/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
wget -P /root/Bucore/.minecraft/libraries/commons-io/commons-io/2.5/ https://libraries.minecraft.net/commons-io/commons-io/2.5/commons-io-2.5.jar
wget -P /root/Bucore/.minecraft/libraries/commons-codec/commons-codec/1.10/ https://libraries.minecraft.net/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
wget -P /root/Bucore/.minecraft/libraries/net/java/jinput/jinput/2.0.5/ https://libraries.minecraft.net/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
wget -P /root/Bucore/.minecraft/libraries/net/java/jutils/jutils/1.0.0/ https://libraries.minecraft.net/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
wget -P /root/Bucore/.minecraft/libraries/com/mojang/brigadier/1.0.17/ https://libraries.minecraft.net/com/mojang/brigadier/1.0.17/brigadier-1.0.17.jar
wget -P /root/Bucore/.minecraft/libraries/com/mojang/datafixerupper/2.0.24/ https://libraries.minecraft.net/com/mojang/datafixerupper/2.0.24/datafixerupper-2.0.24.jar
wget -P /root/Bucore/.minecraft/libraries/com/google/code/gson/gson/2.8.0/ https://libraries.minecraft.net/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
wget -P /root/Bucore/.minecraft/libraries/com/mojang/authlib/1.5.25/ https://libraries.minecraft.net/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
wget -P /root/Bucore/.minecraft/libraries/org/apache/commons/commons-compress/1.8.1/ https://libraries.minecraft.net/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
wget -P /root/Bucore/.minecraft/libraries/org/apache/httpcomponents/httpclient/4.3.3/ https://libraries.minecraft.net/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
wget -P /root/Bucore/.minecraft/libraries/commons-logging/commons-logging/1.1.3/ https://libraries.minecraft.net/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
wget -P /root/Bucore/.minecraft/libraries/org/apache/httpcomponents/httpcore/4.3.2/ https://libraries.minecraft.net/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
wget -P /root/Bucore/.minecraft/libraries/it/unimi/dsi/fastutil/8.2.1/ https://libraries.minecraft.net/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar
wget -P /root/Bucore/.minecraft/libraries/org/apache/logging/log4j/log4j-api/2.8.1/ https://libraries.minecraft.net/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
wget -P /root/Bucore/.minecraft/libraries/org/apache/logging/log4j/log4j-core/2.8.1/ https://libraries.minecraft.net/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
wget -P /root/Bucore/.minecraft/libraries/org/lwjgl/lwjgl/3.2.2/ https://libraries.minecraft.net/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
wget -P /root/Bucore/.minecraft/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/ https://libraries.minecraft.net/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
wget -P /root/Bucore/.minecraft/libraries/org/lwjgl/lwjgl-openal/3.2.2/ https://libraries.minecraft.net/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
wget -P /root/Bucore/.minecraft/libraries/org/lwjgl/lwjgl-opengl/3.2.2/ https://libraries.minecraft.net/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
wget -P /root/Bucore/.minecraft/libraries/org/lwjgl/lwjgl-glfw/3.2.2/ https://libraries.minecraft.net/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
wget -P /root/Bucore/.minecraft/libraries/org/lwjgl/lwjgl-stb/3.2.2/ https://libraries.minecraft.net/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
wget -P /root/Bucore/.minecraft/libraries/org/lwjgl/lwjgl/3.2.2/ https://libraries.minecraft.net/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
wget -P /root/Bucore/.minecraft/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/ https://libraries.minecraft.net/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
wget -P /root/Bucore/.minecraft/libraries/org/lwjgl/lwjgl-openal/3.2.2/ https://libraries.minecraft.net/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
wget -P /root/Bucore/.minecraft/libraries/org/lwjgl/lwjgl-opengl/3.2.2/ https://libraries.minecraft.net/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
wget -P /root/Bucore/.minecraft/libraries/org/lwjgl/lwjgl-glfw/3.2.2/ https://libraries.minecraft.net/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
wget -P /root/Bucore/.minecraft/libraries/org/lwjgl/lwjgl-stb/3.2.2/ https://libraries.minecraft.net/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
wget -P /root/Bucore/.minecraft/libraries/com/mojang/text2speech/1.11.3/ https://libraries.minecraft.net/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar
